export const commonThemeColor = {
  white: '#ffffff',
  black: '#000000',
  modalVisbleBg: 'rgba(0,0,0,0.5)',
  red: '#FF0000',
  blue: '#0088f8',
  gray: '#9E9E9E',
  lightBlue: '#add0ed',
  lightGrey: '#969696',
  inputBackground: '#121212',
  secondary: '#9747FF',
  lightWhite: '#a3a3a3',
  gray91: '#E8E8E8',
  appColor: '#F1D91D',
  greenColor: '#50c878',
  userChatBg: '#FDF9DD',
  otherChatBg: '#E5E5E5',
  appColor01: 'rgba(241, 217, 29, 0.1)',
  appColorOP3: 'rgba(241, 217, 29, 0.3)',
  appColorOP2: 'rgba(241, 217, 29, 0.2)',
  darkGray: '#393E46',
  yellow: '#F1D91D',
  transparent: 'transparent',
  success: '#dfd',
  green: '#0BDA51',
  primaryLightTextColor: '#7D848D',
  // Add new color here
};

export const blackTheme = {
  primary: 'lightBlue',
  background: 'black',
  circleBg: 'green',
  iconBg: 'pink',
  tintColor: 'white',
  card: 'green',
  title: 'green',
  subTitle: 'green',
  description: 'green',
  border: 'white',
  icon: 'green',
  label: 'white',
  inputValue: 'white',
  placeholderText: '#F5F5F5',
  text: 'white',
  gredientBg: ['green', 'red'],
  subtitleText: '#FFFFF0',
  textInputContainer: '#222222',
  appBtnBackColor: '#f1d91d',
  appBtnText: 'black',
  appColor: '#F1D91D',
  appColor01: 'rgba(241, 217, 29, 0.1)',
  svg: 'white',
  modalBackground: 'gray',
  imgModalBackGround: 'gray',
  green: '#0BDA51',
  lightBgAppColor: '#FDF9DE',
  yellowGradient: ['#FFEB3B', '#FBC02D', '#F9A825'],
};

export const whiteTheme = {
  primary: '#9747FF',
  background: 'white',
  circleBg: 'purple',
  iconBg: 'yellow',
  tintColor: 'black',
  card: 'yellow',
  title: 'purple',
  subTitle: 'purple',
  description: 'purple',
  border: 'grey',
  icon: 'purple',
  label: 'yellow',
  inputValue: 'black',
  text: 'black',
  gredientBg: ['purple', 'red'],
  appColor: '#F1D91D',
  appColor01: 'rgba(241, 217, 29, 0.1)',
  primary01: 'rgba(151, 71, 255, 0.1)',
  placeholderText: 'gray',
  textInputContainer: '#F5F5F5',
  appBtnBackColor: 'black',
  appBtnText: 'white',
  modalBackground: 'white',
  subtitleText: '#e5e5e5',
  svg: 'black',
  imgModalBackGround: 'white',
  green: '#0BDA51',
  lightBgAppColor: '#FDF9DE',
  yellowGradient: ['#FFEB3B', '#FBC02D', '#F9A825'],
  textColor: '#1B1E28',
};

export default {commonThemeColor, blackTheme, whiteTheme};
